---
repos:
- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.18
  hooks:
    - id: go-fmt

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-merge-conflict
