frameworkVersion: "3"
service: electronic-tariff-file-rotations

provider:
  name: aws
  region: eu-west-2
  runtime: go1.x
  stage: ${env:STAGE}
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}
  environment:
    ETF_BUCKET: ${env:ETF_BUCKET}

package:
  patterns:
    - "!./**"
    - ./bin/**

functions:
  rotation:
    handler: bin/handler
    events:
      - schedule: cron(0 8 * * ? *) # Run every day at 0800 UTC
