frameworkVersion: "3"
service: electronic-tariff-file-rotations

provider:
  name: aws
  region: eu-west-2
  runtime: go1.x
  stage: ${env:STAGE}
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}
  environment:
    ETF_BUCKET: ${env:ETF_BUCKET}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:DeleteObject
        - s3:GetObject
        - s3:ListBucket
      Resource:
        - "arn:aws:s3:::${env:ETF_BUCKET}"
        - "arn:aws:s3:::${env:ETF_BUCKET}/*"

    - Effect: "Allow"
      Action:
        - kms:GenerateDataKey
        - kms:Decrypt
      Resource:
        - "arn:aws:kms:${self:provider.region}:${aws:accountId}:key/*"

package:
  patterns:
    - "!./**"
    - ./bin/**

functions:
  rotation:
    handler: bin/handler
    events:
      - schedule: cron(0 8 * * ? *) # Run every day at 0800 UTC
