frameworkVersion: "3"
service: reporting-file-rotations

provider:
  name: aws
  region: eu-west-2
  runtime: provided.al2023
  stage: ${env:STAGE}
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}
  environment:
    DEBUG: "false"
    DELETION_CANDIDATE_DAYS: "${env:DELETION_CANDIDATE_DAYS}"
    ETF_BUCKET: "trade-tariff-reporting-${aws:accountId}"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:DeleteObject
        - s3:GetObject
        - s3:ListBucket
      Resource:
        - "arn:aws:s3:::trade-tariff-reporting-${aws:accountId}"
        - "arn:aws:s3:::trade-tariff-reporting-${aws:accountId}/*"

    - Effect: "Allow"
      Action:
        - kms:GenerateDataKey
        - kms:Decrypt
      Resource:
        - "arn:aws:kms:${self:provider.region}:${aws:accountId}:key/*"

package:
  patterns:
    - "!./**"
    - bootstrap

functions:
  rotation:
    handler: bootstrap
    events:
      - schedule: cron(0 8 * * ? *) # Run every day at 0800 UTC

custom:
  logRetentionInDays:
    development: 7
    staging: 14
    production: 30

resources:
  Resources:
    RotationLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:service}-${env:STAGE}-rotation
        RetentionInDays: ${self:custom.logRetentionInDays.${env:STAGE}, 14}