version: 2.1

filter-not-main: &filter-not-main
  filters:
    branches:
      ignore:
        - main
        - /^dependabot/(?!docker/).*/
        - /^hotfix\/.+/

filter-main: &filter-main
  filters:
    branches:
      only:
        - main
        - /^hotfix\/.+/

orbs:
  serverless-framework: circleci/serverless-framework@2.0.1

jobs:
  lint:
    docker:
      - image: cimg/go:1.21.0
    steps:
      - checkout
      - run:
          name: "Install linter"
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b $(go env GOPATH)/bin v1.54.2
      - run: make lint

workflows:
  version: 2

  deploy-to-development:
    jobs:
      - lint:
          <<: *filter-not-main
