name: Lint and Deploy to Development

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-west-2
  IAM_ROLE_ARN: arn:aws:iam::844815912454:role/GithubActions-Serverless-Lambda-Role
  DEPLOYMENT_BUCKET: trade-tariff-lambda-deployment-844815912454
  STAGE: development

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v7

        - uses: actions/setup-go@v7.0.0
          with:
            go-version: '1.26.6'

        - name: Restore Go modules cache
          uses: actions/cache@v6.1.0
          with:
            path: |
              ~/go/pkg/mod
            key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              ${{ runner.os }}-go-

        - uses: golangci/golangci-lint-action@v6.5.2
          with:
            version: v1.64.2
            working-directory: electronic-tariff-file-rotations

    deploy:
      needs: lint
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v7

        - uses: actions/setup-node@v7.0.0
          with:
            node-version: 'lts/*'

        - uses: aws-actions/configure-aws-credentials@v6.2.3
          with:
            role-to-assume: ${{ env.IAM_ROLE_ARN }}
            aws-region: ${{ env.AWS_REGION }}

        - run: npm install -g serverless@^3
        - run: make deploy-development
