name: Lint and Deploy to Development

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-west-2
  IAM_ROLE_ARN: arn:aws:iam::844815912454:role/GithubActions-Serverless-Lambda-Role
  DEPLOYMENT_BUCKET: trade-tariff-lambda-deployment-844815912454
  STAGE: development

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-go@v5
          with:
            go-version: '1.21'

        - name: Restore Go modules cache
          uses: actions/cache@v4
          with:
            path: |
              ~/go/pkg/mod
            key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              ${{ runner.os }}-go-

        - name: Install GolangCI-Lint
          run: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.2
        - run: make lint


    deploy:
      needs: lint
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-node@v4
          with:
            node-version: 'lts/*'

        - uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: ${{ env.IAM_ROLE_ARN }}
            aws-region: ${{ env.AWS_REGION }}

        - run: npm install -g serverless@^3
        - run: make deploy-development
